seed: 42
n_splits: 5

data:
  train_path: data/train.csv
  test_path: data/test.csv
  target: diagnosed_diabetes
  id_col: id

feature_engineering: true

model:
  name: catboost
  params:
    learning_rate: 0.05
    depth: 8
    n_estimators: 1500
    l2_leaf_reg: 3.0
    loss_function: Logloss
    eval_metric: AUC
